apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system # Flux default namespace
spec:
  interval: 5m # How often to apply changes
  path: ./apps/base # Path within the Git repo to the app manifests
  prune: true # Automatically delete resources removed from Git
  sourceRef:
    kind: GitRepository
    name: my-app-source # Matches the name in gitrepository.yaml
  targetNamespace: demo # Alterado de default para demo
  timeout: 2m # Timeout for operations
  dependsOn:
    - name: infrastructure
      namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-deployment
      namespace: demo 