apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: demo
  labels:
    app: hello-world
    environment: demo
  annotations:
    oci.oraclecloud.com/load-balancer-shape: "flexible"
    oci.oraclecloud.com/load-balancer-shape-flex-min: "10"
    oci.oraclecloud.com/load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer # Use ClusterIP if you don't want an external LB, or NodePort
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 80
      name: http 